name: inferno
description: Automatically create Dart classes that match the structure of your JSON files.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  json_serializable: ^6.5.1
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  test: ^1.16.0
